name: masslearn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - dash>=2.14
  - dash-bootstrap-components>=1.5
  - plotly>=5.18
  - lz4>=4.3
  - diskcache>=5.6
  - pandas>=2.0
  - numpy>=1.24
  - scipy>=1.10
  - scikit-learn>=1.3
  - statsmodels>=0.14
  - networkx>=3.1
  - matplotlib>=3.7
  - ipywidgets>=8.0
  - pyqt>=5.15
  - pyqtwebengine>=5.15
  - tqdm>=4.66
  - pip:
      - pymzml>=2.5
      - pyteomics>=4.6
      - neatms>=1.2
      - peakutils>=1.3
